spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate:
        show-sql: false
    show-sql: false
  config:
    use-legacy-processing: true
  profiles:
    active: development

logging:
  level:
    ROOT: INFO
    ru.chibisov: INFO
    ru.chibisov.audit: INFO
    org.springframework: INFO
  appenders:
    console:
      enabled: false
    file:
      enabled: true

scheduling:
  cron:
    enabled: true
    expression: "0 * * * * *"

audit:
  db:
    enabled: true

